      - name: Ensure development tools are installed for Fluentbit Dev
        ansible.builtin.apt:
          name: '{{item}}'
          state: latest
        loop:
          - cmake
          - flex #"
          - bison #"
          - libyaml-dev #
          - libssl-dev
          - libsystemd-dev  
          - pkg-config 


