version: '2'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:5.0.0
  #DB in share for persistence
    volumes:
#       - vol_mongodb:/data/db
      - /var/logging/mongodb:/data/db
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.6/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
#    container_name: elasticsearch
    #data folder in share for persistence
    volumes:
#       - vol_elastic:/usr/share/elasticsearch/data
      - /var/logging/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - TZ=Europe/Amsterdam
      - transport.host=localhost
      - network.host=0.0.0.0
      - node.max_local_storage_nodes=4
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
#    image: graylog/graylog:4.3
#    image: graylog/graylog:5.0
    image: graylog/graylog:5.0.1
    user: 1100:1100
#    container_name: graylog
    #journal and config directories in local NFS share for persistence
    volumes:
#       - vol_graylog_1:/usr/share/graylog/data/journal
#       - vol_graylog_2:/usr/share/graylog/data/config
      - /var/logging/graylog/journal:/usr/share/graylog/data/journal
      - /var/logging/graylog/config:/usr/share/graylog/data/config

    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=forpasswordencryption
      # Password: admin
      - TZ=Europe/Amsterdam
#      - GRAYLOG_ROOT_TIMEZONE=UTC
      - GRAYLOG_ROOT_TIMEZONE=Europe/Amsterdam
      - GRAYLOG_ROOT_PASSWORD_SHA2=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxx
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:7555
      - GRAYLOG_HTTP_EXTERNAL_URI=http://192.168.10.152:7555/
      - GRAYLOG_TRANSPORT_EMAIL_WEB_INTERFACE_URL=http://192.168.10.152:7555
      - GRAYLOG_TRANSPORT_EMAIL_HOSTNAME=smtp.example.com
      - GRAYLOG_TRANSPORT_EMAIL_ENABLED=true
      - GRAYLOG_TRANSPORT_EMAIL_PORT=25
      - GRAYLOG_TRANSPORT_EMAIL_USE_AUTH=false
      - GRAYLOG_TRANSPORT_EMAIL_USE_TLS=false
      - GRAYLOG_TRANSPORT_EMAIL_USE_SSL=false
      - GRAYLOG_TRANSPORT_FROM_EMAIL=youremail@yourdomain.com
      - GRAYLOG_TRANSPORT_SUBJECT_PREFIX=[graylog]
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 7555:7555
      # Syslog TCP
      - 8514:8514
      # Syslog UDP
      - 8514:8514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
# volumes:
#   vol_mongodb:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /var/logging/mongodb
#   vol_elastic:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /var/logging/elasticsearch/data
#   vol_graylog_1:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /var/logging/graylog/data/journal
#   vol_graylog_2:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /var/logging/graylog/data/config
